"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class rc_control_command_lcmt(object):
    __slots__ = ["mode", "gait_type", "v_des", "omega_des"]

    __typenames__ = ["double", "int32_t", "double", "double"]

    __dimensions__ = [None, None, [3], [3]]

    def __init__(self):
        self.mode = 0.0
        self.gait_type = 0
        self.v_des = [ 0.0 for dim0 in range(3) ]
        self.omega_des = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(rc_control_command_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">di", self.mode, self.gait_type))
        buf.write(struct.pack('>3d', *self.v_des[:3]))
        buf.write(struct.pack('>3d', *self.omega_des[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != rc_control_command_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return rc_control_command_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = rc_control_command_lcmt()
        self.mode, self.gait_type = struct.unpack(">di", buf.read(12))
        self.v_des = struct.unpack('>3d', buf.read(24))
        self.omega_des = struct.unpack('>3d', buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if rc_control_command_lcmt in parents: return 0
        tmphash = (0x502e774506256d4c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if rc_control_command_lcmt._packed_fingerprint is None:
            rc_control_command_lcmt._packed_fingerprint = struct.pack(">Q", rc_control_command_lcmt._get_hash_recursive([]))
        return rc_control_command_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", rc_control_command_lcmt._get_packed_fingerprint())[0]

