/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class rc_control_command_lcmt implements lcm.lcm.LCMEncodable
{
    public double mode;
    public int gait_type;
    public double v_des[];
    public double omega_des[];
 
    public rc_control_command_lcmt()
    {
        v_des = new double[3];
        omega_des = new double[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x502e774506256d4cL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.rc_control_command_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.rc_control_command_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeDouble(this.mode); 
 
        outs.writeInt(this.gait_type); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.v_des[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.omega_des[a]); 
        }
 
    }
 
    public rc_control_command_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public rc_control_command_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.rc_control_command_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.rc_control_command_lcmt o = new lcmtypes.rc_control_command_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.mode = ins.readDouble();
 
        this.gait_type = ins.readInt();
 
        this.v_des = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.v_des[a] = ins.readDouble();
        }
 
        this.omega_des = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.omega_des[a] = ins.readDouble();
        }
 
    }
 
    public lcmtypes.rc_control_command_lcmt copy()
    {
        lcmtypes.rc_control_command_lcmt outobj = new lcmtypes.rc_control_command_lcmt();
        outobj.mode = this.mode;
 
        outobj.gait_type = this.gait_type;
 
        outobj.v_des = new double[(int) 3];
        System.arraycopy(this.v_des, 0, outobj.v_des, 0, 3); 
        outobj.omega_des = new double[(int) 3];
        System.arraycopy(this.omega_des, 0, outobj.omega_des, 0, 3); 
        return outobj;
    }
 
}

